name: Java CI with Maven

on:
  push:
    branches: [ "master2" ]
  pull_request:
    branches: [ "master2" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Setup Maven
      uses: stCarolas/setup-maven@v5
      with:
        maven-version: 3.8.2
          
    - name: Build with Maven
      run: mvn package --file JtProject/pom.xml -DskipTests

    - name: Debug Environment Variables
      run: |
        echo "SONAR_URL=${{ secrets.SONAR_URL }}"
        echo "SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}"

